version: "2.4"
services:
  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab-web'
    container_name: gitlab-web
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab-web'
        #registry['enable'] = true
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - '$GITLAB_HOME/gitlab/config:/etc/gitlab'
      - '$GITLAB_HOME/gitlab/logs:/var/log/gitlab'
      - '$GITLAB_HOME/gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab-network

  gitlab-runner1:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner1
    hostname: 'gitlab-runner1'
    volumes:
      - '$GITLAB_HOME/gitlab-runner1-config:/etc/gitlab-runner:Z'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network


networks:
  gitlab-network:
    name: gitlab-network
